"""
Django settings for CLAS project.

Generated by 'django-admin startproject' using Django 5.2.
"""

from pathlib import Path
import os
import logging

import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Initialize environment variables
env = environ.Env(
    # Set casting and default values
    DEBUG=(bool, False),
    ALLOWED_HOSTS=(list, ['*']),
)

# Read .env file if it exists
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

# Initialize logger for use in settings
logger = logging.getLogger(__name__)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY', default='django-insecure-default-key-change-me')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG') 

# ✅ Allow all hosts specified in environment or default to '*'
ALLOWED_HOSTS = env('ALLOWED_HOSTS')

# ✅ Disable trailing slash redirect for service worker and other files
APPEND_SLASH = env.bool('APPEND_SLASH', default=False)

# ✅ File Upload Configuration
# Allow larger file uploads for lesson plans, videos, etc.
# Set to 100MB to handle large video files and documents
FILE_UPLOAD_MAX_MEMORY_SIZE = 104857600  # 100 MB
DATA_UPLOAD_MAX_MEMORY_SIZE = 104857600  # 100 MB
FILE_UPLOAD_PERMISSIONS = 0o644
FILE_UPLOAD_DIRECTORY_PERMISSIONS = 0o755

# Temporary file upload settings
FILE_UPLOAD_TEMP_DIR = BASE_DIR / 'tmp'
os.makedirs(FILE_UPLOAD_TEMP_DIR, exist_ok=True)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'class',
    'widget_tweaks',
    'django.contrib.humanize',  # For better number formatting
]

# Static files optimization
STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
]

# Enable static file compression in production
if not DEBUG:
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
    
    # Additional compression settings
    WHITENOISE_USE_FINDERS = True
    WHITENOISE_AUTOREFRESH = False
    WHITENOISE_SKIP_COMPRESS_EXTENSIONS = ['jpg', 'jpeg', 'png', 'gif', 'webp', 'zip', 'gz', 'tgz', 'bz2', 'tbz', 'xz', 'br']
    
    # ✅ CACHE CONTROL FOR STATIC FILES
    # Don't cache HTML files, but cache other assets for 1 year
    WHITENOISE_MAX_AGE = 31536000  # 1 year for versioned assets
else:
    STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.StaticFilesStorage'
    WHITENOISE_MAX_AGE = 0  # No caching in development

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    # ✅ CACHE CONTROL MIDDLEWARE - Must be early
    'class.cache_control_middleware.CacheControlMiddleware',
    # ✅ PWA Auth Bypass - MUST BE BEFORE AuthenticationMiddleware
    'class.pwa_auth_bypass_middleware.PWAAuthBypassMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    # ✅ File Upload Error Handling
    'class.file_upload_middleware.FileUploadErrorMiddleware',
    # ✅ PWA Headers Middleware
    'class.pwa_middleware.PWAHeadersMiddleware',
    # ✅ DATABASE CONNECTION HANDLING (FIRST - before other middleware)
    'class.db_connection_middleware.DatabaseConnectionMiddleware',
    # ✅ SESSION MANAGEMENT (NO TIMEOUT - USERS STAY LOGGED IN)
    'class.services.session_auth_fix.LocalStorageCleanupMiddleware',
    'class.services.session_auth_fix.URLAccessControlMiddleware',
    # Performance optimization
    'class.performance_middleware.PerformanceOptimizationMiddleware',
    'class.performance_middleware.BrowserCachingMiddleware',
    'class.performance_middleware.ResponseCompressionMiddleware',
    # Error handling
    'class.session_timeout_middleware.UserFriendlyErrorMiddleware',
    'class.middleware.MessageCleanupMiddleware',
    'class.middleware.DebugMessageSuppressMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'CLAS.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'Templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'CLAS.wsgi.application'


# Database
# Use DATABASE_URL from .env or environment variables
DATABASES = {
    'default': env.db('DATABASE_URL', default='DATABASE_URL_REMOVED')
}

# Ensure OPTIONS are handled for Neon/CI
if DATABASES['default']['ENGINE'] == 'django.db.backends.postgresql':
    DATABASES['default']['OPTIONS'] = {
        'sslmode': env('DB_SSLMODE', default='require'),
        'connect_timeout': 10,
        'options': '-c statement_timeout=60000'
    }
DATABASES['default']['CONN_MAX_AGE'] = 60
DATABASES['default']['CONN_HEALTH_CHECKS'] = True
DATABASES['default']['AUTOCOMMIT'] = True

# ===== PERFORMANCE OPTIMIZATIONS =====

# Caching Configuration - Optimized for Performance
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
        'TIMEOUT': 600,  # 10 minutes default timeout
        'OPTIONS': {
            'MAX_ENTRIES': 2000,  # Increased for better caching
            'CULL_FREQUENCY': 3,
        }
    },
    'sessions': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'session-cache',
        'TIMEOUT': 7200,  # 2 hours for sessions
    },
    'curriculum': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'curriculum-cache',
        'TIMEOUT': 7200,  # 2 hours for curriculum content
    },
    'dashboard': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'dashboard-cache',
        'TIMEOUT': 600,  # 10 minutes for dashboard stats (increased from 5)
    }
}

# Cache middleware settings - Optimized
CACHE_MIDDLEWARE_ALIAS = 'default'
# ✅ FIX: Disable caching in development (DEBUG=True) so you see data changes immediately
# In production (DEBUG=False), cache for 10 minutes
CACHE_MIDDLEWARE_SECONDS = 600 if not DEBUG else 0 

# HTTP Cache Headers for static files
CACHE_CONTROL_MAX_AGE = 31536000  # 1 year for static files
CACHE_MIDDLEWARE_KEY_PREFIX = 'clas'

# Session Configuration for Performance
SESSION_ENGINE = 'django.contrib.sessions.backends.cached_db'
SESSION_CACHE_ALIAS = 'sessions'
SESSION_COOKIE_AGE = 31536000  # 1 year (keep users logged in)
SESSION_SAVE_EVERY_REQUEST = False  # Only save when modified (better performance)
SESSION_COOKIE_SECURE = not DEBUG  # HTTPS only in production
SESSION_COOKIE_HTTPONLY = True  # Prevent JavaScript access
SESSION_COOKIE_SAMESITE = 'Lax'  # CSRF protection

# Session timeout configuration (in seconds)
SESSION_TIMEOUT = 31536000  # 1 year - keep users logged in
SESSION_EXPIRE_AT_BROWSER_CLOSE = False  # Sessions persist after browser closes

# Database Query Optimization
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Logging Configuration for Performance Monitoring
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs' / 'django.log',
            'formatter': 'verbose',
        },
        'console': {
            'level': 'DEBUG' if DEBUG else 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': True,
        },
        'django.db.backends': {
            'handlers': ['file'],
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': False,
        },
        'class': {  # Your app logger
            'handlers': ['file', 'console'],
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': True,
        },
    },
}

# Create logs directory if it doesn't exist
os.makedirs(BASE_DIR / 'logs', exist_ok=True)


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

STATICFILES_DIRS = [
    BASE_DIR / "static", 
]

# Media files (User uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Create media directory if it doesn't exist with proper permissions
try:
    os.makedirs(MEDIA_ROOT, mode=0o775, exist_ok=True)
except Exception as e:
    logger.warning(f"Could not create media directory: {e}")

# Ensure media directory is writable
if os.path.exists(MEDIA_ROOT):
    try:
        os.chmod(MEDIA_ROOT, 0o775)
    except Exception as e:
        logger.warning(f"Could not set media directory permissions: {e}")

# AWS S3 Configuration for Static Files (Optional - uncomment to use S3)
# Uncomment these lines if you want to use AWS S3 for static files
# import boto3
# AWS_ACCESS_KEY_ID = os.environ.get('AWS_ACCESS_KEY_ID')
# AWS_SECRET_ACCESS_KEY = os.environ.get('AWS_SECRET_ACCESS_KEY')
# AWS_STORAGE_BUCKET_NAME = os.environ.get('AWS_STORAGE_BUCKET_NAME', 'your-bucket-name')
# AWS_S3_REGION_NAME = os.environ.get('AWS_S3_REGION_NAME', 'us-east-1')
# AWS_S3_CUSTOM_DOMAIN = f'{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com'
# AWS_S3_OBJECT_PARAMETERS = {'CacheControl': 'max-age=86400'}
# AWS_LOCATION = 'static'
# STATIC_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/{AWS_LOCATION}/'
# STATICFILES_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'




# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

AUTH_USER_MODEL = 'class.User'
