# Generated by Django 5.1.15 on 2026-01-24 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0026_add_performance_indexes_safe'),
    ]

    operations = [
    ]
