# Generated by Django 5.1.15 on 2026-01-12 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0029_phase1_optimization_status_fields'),
    ]

    operations = [
    ]
