# Generated by Django 5.1.15 on 2026-03-08 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0055_simplify_feedback_models'),
        ('class', '0054_studentguardian'),
    ]

    operations = [
    ]
