# Generated by Django 5.1.15 on 2026-03-08 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0057_make_studentfeedback_student_required'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessionfeedback',
            name='additional_notes',
        ),
        migrations.RemoveField(
            model_name='sessionfeedback',
            name='areas_for_improvement',
        ),
        migrations.RemoveField(
            model_name='sessionfeedback',
            name='content_difficulty_rating',
        ),
        migrations.RemoveField(
            model_name='sessionfeedback',
            name='facilitator_satisfaction',
        ),
        migrations.RemoveField(
            model_name='sessionfeedback',
            name='is_complete',
        ),
        migrations.RemoveField(
            model_name='sessionfeedback',
            name='learning_objectives_met',
        ),
        migrations.RemoveField(
            model_name='sessionfeedback',
            name='next_session_preparation',
        ),
        migrations.RemoveField(
            model_name='sessionfeedback',
            name='session_completion_percentage',
        ),
        migrations.RemoveField(
            model_name='sessionfeedback',
            name='student_participation_notes',
        ),
        migrations.RemoveField(
            model_name='sessionfeedback',
            name='time_management_rating',
        ),
        migrations.RemoveField(
            model_name='sessionfeedback',
            name='what_went_well',
        ),
        migrations.RemoveField(
            model_name='studentfeedback',
            name='additional_suggestions',
        ),
        migrations.RemoveField(
            model_name='studentfeedback',
            name='anonymous_student_id',
        ),
        migrations.RemoveField(
            model_name='studentfeedback',
            name='improvement_suggestions',
        ),
        migrations.RemoveField(
            model_name='studentfeedback',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='studentfeedback',
            name='session_highlights',
        ),
        migrations.RemoveField(
            model_name='studentfeedback',
            name='session_rating',
        ),
        migrations.RemoveField(
            model_name='studentfeedback',
            name='teacher_clarity',
        ),
        migrations.RemoveField(
            model_name='studentfeedback',
            name='topic_understanding',
        ),
        migrations.AddField(
            model_name='sessionfeedback',
            name='day_reflection',
            field=models.TextField(blank=True, help_text='How was the day? - Free text reflection'),
        ),
    ]
