# Generated by Django 5.1.15 on 2026-03-09 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0058_remove_sessionfeedback_additional_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actualsession',
            name='is_conduct_completed',
            field=models.BooleanField(default=False, help_text='Whether the conduct step (Step 3) was marked as completed'),
        ),
    ]
