# Generated by Django 5.1.15 on 2026-03-09 11:23

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0059_actualsession_is_conduct_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassSessionProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('is_grouped', models.BooleanField(default=False)),
                ('grouped_session_id', models.UUIDField(blank=True, null=True)),
                ('group_classes_info', models.TextField(blank=True, help_text='Names of classes in the group')),
                ('day_number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_progress', to='class.classsection')),
            ],
            options={
                'verbose_name': 'Class Session Progress',
                'verbose_name_plural': 'Class Session Progress Logs',
                'ordering': ['-date', '-created_at'],
                'unique_together': {('date', 'class_section')},
            },
        ),
    ]
