# Generated by Django 5.1.15 on 2026-03-09 19:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0060_classsessionprogress'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionStepStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_date', models.DateField(help_text='The calendar date when this session was conducted')),
                ('step_number', models.PositiveIntegerField(choices=[(1, 'Lesson Plan'), (2, 'Preparation'), (3, 'Conduct'), (4, 'Attendance'), (5, 'Upload'), (6, 'Feedback'), (7, 'Reward')], help_text='Which workflow step (1-7)')),
                ('is_completed', models.BooleanField(default=False, help_text='Whether this step is completed')),
                ('step_content', models.JSONField(blank=True, default=dict, help_text='JSON data associated with this step (images, notes, etc.)')),
                ('completed_at', models.DateTimeField(blank=True, help_text='When this step was marked as completed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('facilitator', models.ForeignKey(blank=True, help_text='Facilitator who completed this step', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='step_statuses', to=settings.AUTH_USER_MODEL)),
                ('planned_session', models.ForeignKey(help_text='Reference to the planned session (day)', on_delete=django.db.models.deletion.CASCADE, related_name='step_statuses', to='class.plannedsession')),
            ],
            options={
                'verbose_name': 'Session Step Status',
                'verbose_name_plural': 'Session Step Statuses',
                'ordering': ['session_date', 'step_number'],
                'indexes': [models.Index(fields=['planned_session', 'session_date'], name='class_sessi_planned_dad5df_idx'), models.Index(fields=['session_date', 'step_number'], name='class_sessi_session_b8de2d_idx'), models.Index(fields=['facilitator', 'session_date'], name='class_sessi_facilit_c47a00_idx')],
                'unique_together': {('planned_session', 'session_date', 'step_number')},
            },
        ),
    ]
