# Generated by Django 5.1.15 on 2026-04-02 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0061_add_session_step_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionfeedback',
            name='rating',
            field=models.IntegerField(choices=[(5, 'Excellent'), (4, 'Good'), (3, 'Average'), (2, 'Below Average'), (1, 'Poor')], default=5, help_text='Session rating out of 5'),
        ),
    ]
