# Generated by Django 5.1.15 on 2026-04-02 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0062_sessionfeedback_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionfeedback',
            name='rating',
            field=models.IntegerField(default=10, help_text='Session rating out of 10'),
        ),
    ]
