# Generated by Django 5.1.15 on 2026-04-17 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0063_alter_sessionfeedback_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curriculumsession',
            name='template',
        ),
        migrations.RemoveField(
            model_name='sessionusagelog',
            name='facilitator',
        ),
        migrations.RemoveField(
            model_name='sessionusagelog',
            name='school',
        ),
        migrations.RemoveField(
            model_name='sessionusagelog',
            name='session',
        ),
        migrations.AlterUniqueTogether(
            name='sessionversionhistory',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='sessionversionhistory',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='sessionversionhistory',
            name='session',
        ),
        migrations.AlterModelOptions(
            name='actualsession',
            options={'verbose_name': 'Actual Session'},
        ),
        migrations.DeleteModel(
            name='SessionTemplate',
        ),
        migrations.DeleteModel(
            name='SessionUsageLog',
        ),
        migrations.DeleteModel(
            name='SessionVersionHistory',
        ),
    ]
