# Generated by Django 5.1.15 on 2026-04-18 08:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0064_remove_curriculumsession_template_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAttendanceSummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('present_count', models.PositiveIntegerField(default=0)),
                ('absent_count', models.PositiveIntegerField(default=0)),
                ('leave_count', models.PositiveIntegerField(default=0)),
                ('last_marked_at', models.DateTimeField(blank=True, help_text='Last time any attendance was marked for this student', null=True)),
                ('total_sessions_conducted', models.PositiveIntegerField(default=0, help_text='Total conducted sessions for the class at last summary update')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrollment', models.OneToOneField(help_text='Direct link to student enrollment', on_delete=django.db.models.deletion.CASCADE, related_name='attendance_summary', to='class.enrollment')),
            ],
            options={
                'verbose_name': 'Student Attendance Summary',
                'verbose_name_plural': 'Student Attendance Summaries',
                'indexes': [models.Index(fields=['enrollment', 'updated_at'], name='att_summary_perf_idx')],
            },
        ),
    ]
