# Generated by Django 5.1.15 on 2026-04-18 09:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0065_studentattendancesummary'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacilitatorAttendanceSummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sessions_conducted', models.PositiveIntegerField(default=0, help_text='Total number of sessions marked as CONDUCTED')),
                ('schools_count', models.PositiveIntegerField(default=0, help_text='Current number of active school assignments')),
                ('average_rating', models.FloatField(default=0.0, help_text='Lifetime average rating from FeedbackAnalytics')),
                ('last_active_date', models.DateField(blank=True, help_text='Date of the last conducted session', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('facilitator', models.OneToOneField(help_text='Link to the facilitator user', on_delete=django.db.models.deletion.CASCADE, related_name='facilitator_summary', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Facilitator Attendance Summary',
                'verbose_name_plural': 'Facilitator Attendance Summaries',
                'indexes': [models.Index(fields=['facilitator', 'updated_at'], name='fac_summary_perf_idx')],
            },
        ),
    ]
