# Generated by Django 5.1.15 on 2026-04-20 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0066_facilitatorattendancesummary'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeacherFeedback',
        ),
    ]
