# Generated by Django 5.1.15 on 2026-04-28 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0015b_add_curriculum_session_indexes'),
        ('class', '0068_remove_actualsession_class_actua_planned_f63c56_idx_and_more'),
    ]

    operations = [
    ]
