# Generated by Django 5.1.15 on 2026-05-01 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0069_merge_20260428_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonplanupload',
            name='lesson_plan_file',
            field=models.FileField(help_text='Uploaded lesson plan file', upload_to='clas/lessonplan/%Y/%m/'),
        ),
    ]
