# Generated by Django 5.1.15 on 2026-05-01 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0070_alter_lessonplanupload_lesson_plan_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonplanupload',
            name='direct_url',
            field=models.URLField(blank=True, help_text='Permanent full URL to the file', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='lessonplanupload',
            name='lesson_plan_file',
            field=models.FileField(help_text='The actual lesson plan file', upload_to='clas/lessonplan/%Y/%m/'),
        ),
    ]
