# Generated by hand to fix missing ManyToMany tables for custom User model

from django.db import migrations

def create_missing_m2m_tables(apps, schema_editor):
    User = apps.get_model('class', 'User')
    db_tables = schema_editor.connection.introspection.table_names()
    
    # 1. Fix User_groups (class_user_groups)
    groups_through = User._meta.get_field('groups').remote_field.through
    if groups_through._meta.db_table not in db_tables:
        print(f"Creating missing table: {groups_through._meta.db_table}")
        schema_editor.create_model(groups_through)
    else:
        print(f"Table {groups_through._meta.db_table} already exists.")
        
    # 2. Fix User_user_permissions (class_user_user_permissions)
    perms_through = User._meta.get_field('user_permissions').remote_field.through
    if perms_through._meta.db_table not in db_tables:
        print(f"Creating missing table: {perms_through._meta.db_table}")
        schema_editor.create_model(perms_through)
    else:
        print(f"Table {perms_through._meta.db_table} already exists.")

class Migration(migrations.Migration):

    dependencies = [
        ('class', '0071_lessonplanupload_direct_url_and_more'),
    ]

    operations = [
        migrations.RunPython(create_missing_m2m_tables, migrations.RunPython.noop),
    ]
