# Generated by Django 5.1.15 on 2026-07-08 20:12

from ..models import facilitator_task, school, students
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0072_fix_missing_m2m_tables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilitatortask',
            name='media_file',
            field=models.FileField(blank=True, help_text='Photo or video file', null=True, upload_to=facilitator_task.facilitator_task_upload_path),
        ),
        migrations.AlterField(
            model_name='lessonplanupload',
            name='lesson_plan_file',
            field=models.FileField(help_text='The actual lesson plan file', upload_to=students.lesson_plan_upload_path),
        ),
        migrations.AlterField(
            model_name='school',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=school.school_logo_path),
        ),
        migrations.AlterField(
            model_name='school',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=school.school_profile_image_path),
        ),
        migrations.AlterField(
            model_name='sessionreward',
            name='reward_photo',
            field=models.ImageField(blank=True, help_text='Photo of reward/student', null=True, upload_to=students.session_reward_upload_path),
        ),
    ]
