# Generated by Django 5.1.15 on 2026-07-08 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0073_alter_facilitatortask_media_file_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='plannedsession',
            name='unique_planned_session_non_grouped',
        ),
        migrations.RemoveConstraint(
            model_name='plannedsession',
            name='unique_planned_session_grouped',
        ),
        migrations.RemoveIndex(
            model_name='plannedsession',
            name='class_plann_class_s_4196f6_idx',
        ),
        migrations.RemoveIndex(
            model_name='plannedsession',
            name='class_plann_class_s_a86331_idx',
        ),
        migrations.RemoveIndex(
            model_name='plannedsession',
            name='class_plann_grouped_6e7056_idx',
        ),
        migrations.RemoveIndex(
            model_name='sessionstepstatus',
            name='class_sessi_planned_dad5df_idx',
        ),
        migrations.AlterUniqueTogether(
            name='actualsession',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='lessonplanupload',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='sessionpreparationchecklist',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='sessionstepstatus',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='plannedsession',
            name='class_section',
        ),
        migrations.RemoveField(
            model_name='plannedsession',
            name='grouped_session_id',
        ),
        migrations.AddField(
            model_name='actualsession',
            name='class_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actual_sessions', to='class.classsection'),
        ),
        migrations.AddField(
            model_name='lessonplanupload',
            name='class_section',
            field=models.ForeignKey(blank=True, help_text='Reference to the class section', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lesson_plan_uploads', to='class.classsection'),
        ),
        migrations.AddField(
            model_name='sessionpreparationchecklist',
            name='class_section',
            field=models.ForeignKey(blank=True, help_text='Reference to class section', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preparation_checklists', to='class.classsection'),
        ),
        migrations.AddField(
            model_name='sessionstepstatus',
            name='class_section',
            field=models.ForeignKey(blank=True, help_text='Reference to class section', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='step_statuses', to='class.classsection'),
        ),
        migrations.AlterField(
            model_name='plannedsession',
            name='day_number',
            field=models.PositiveIntegerField(help_text='Logical day number (Day 1, Day 2, ...)', unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='actualsession',
            unique_together={('class_section', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='lessonplanupload',
            unique_together={('class_section', 'planned_session', 'facilitator')},
        ),
        migrations.AlterUniqueTogether(
            name='sessionpreparationchecklist',
            unique_together={('class_section', 'planned_session', 'facilitator')},
        ),
        migrations.AlterUniqueTogether(
            name='sessionstepstatus',
            unique_together={('class_section', 'planned_session', 'session_date', 'step_number')},
        ),
        migrations.AddIndex(
            model_name='plannedsession',
            index=models.Index(fields=['day_number'], name='class_plann_day_num_3742aa_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionstepstatus',
            index=models.Index(fields=['class_section', 'planned_session', 'session_date'], name='class_sessi_class_s_255ec0_idx'),
        ),
    ]
