# Generated by Django 5.1.15 on 2026-07-29 14:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0074_remove_plannedsession_unique_planned_session_non_grouped_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('role_type', models.CharField(choices=[('GUEST_TEACHER', 'Guest Teacher'), ('GUEST_SPEAKER', 'Guest Speaker'), ('BOTH', 'Both')], default='GUEST_TEACHER', max_length=50)),
                ('organization_type', models.CharField(choices=[('COMPANY', 'Company'), ('INDIVIDUAL', 'Individual'), ('NGO', 'NGO'), ('ACADEMIC', 'Academic'), ('OTHER', 'Other')], default='INDIVIDUAL', max_length=50)),
                ('organization_name', models.CharField(blank=True, default='', max_length=255)),
                ('personal_email', models.EmailField(blank=True, default='', max_length=254)),
                ('work_email', models.EmailField(blank=True, default='', max_length=254)),
                ('country', models.CharField(default='India', max_length=100)),
                ('city', models.CharField(default='Bangalore', max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('linkedin_profile', models.URLField(blank=True, default='', max_length=500)),
                ('regular_volunteering', models.BooleanField(default=False)),
                ('frequency_per_month', models.PositiveIntegerField(default=0)),
                ('interested_area', models.CharField(blank=True, default='', max_length=255)),
                ('interested_topic', models.CharField(blank=True, default='', max_length=255)),
                ('preferred_day', models.CharField(choices=[('NONE', 'None'), ('MONDAY', 'Monday'), ('TUESDAY', 'Tuesday'), ('WEDNESDAY', 'Wednesday'), ('THURSDAY', 'Thursday'), ('FRIDAY', 'Friday'), ('SATURDAY', 'Saturday'), ('SUNDAY', 'Sunday')], default='NONE', max_length=50)),
                ('preferred_class', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
