# Generated by Django 5.1.15 on 2026-07-29 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0075_volunteer'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendardate',
            name='volunteer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendar_dates', to='class.volunteer'),
        ),
        migrations.AlterField(
            model_name='calendardate',
            name='date_type',
            field=models.SmallIntegerField(choices=[(1, 'Planned Session'), (2, 'Holiday / No Session'), (3, 'Office Work / Task'), (4, 'Guest Teacher'), (5, 'Guest Speaker'), (6, 'Other')], default=1, help_text='Type: 1=Session, 2=Holiday, 3=Office Work, 4=Guest Teacher, 5=Guest Speaker, 6=Other'),
        ),
    ]
