# Generated by Django 5.1.15 on 2026-07-29 15:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0076_calendardate_volunteer_alter_calendardate_date_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendardate',
            name='coordinator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coordinated_dates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='calendardate',
            name='facilitator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guest_facilitated_dates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='calendardate',
            name='meeting_link',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='calendardate',
            name='meeting_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='calendardate',
            name='topic',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
