# Generated by Django 5.1.15 on 2026-07-29 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0077_calendardate_coordinator_calendardate_facilitator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendardate',
            name='end_time',
            field=models.TimeField(blank=True, help_text='End time for the session/office work', null=True),
        ),
        migrations.AlterField(
            model_name='calendardate',
            name='time',
            field=models.TimeField(blank=True, help_text='Start time for the session/office work', null=True),
        ),
    ]
